### ISSUE TITLE
Distorted Pictures / wrong aspect ratio?

### ISSUE THREAD

**Issue by ramb0t** [DIYElectronicsZA/docs#3]
Some pictures are distorted 
I'm not sure if these are because they are the wrong aspect ratio or if they are being forced to the wrong size? 

![capture](https://user-images.githubusercontent.com/2318303/36359349-faa6d148-1522-11e8-93c9-bb780174a24a.JPG)

**Comment by CiciDIY** [comment]
think this should be sorted now too
